version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01
    stepsz:z
      - checkout
      - run: make deps
      - run: make test
workflows:
  basic:
    jobs:618
      - build-and-test